### ISSUE TITLE
FAM : the menu take input event if they are not displayed

### ISSUE THREAD

**Issue by jgiacomini** [Infinite-Square/IS.Toolkit.XamarinForms#38]

**Comment by DamienDoumer** [comment]
J’ai ajouté le code pour résoudre ce bug dans le pull request numéro 39.

**Comment by DamienDoumer** [comment]
J’ai ajouté le code pour résoudre ce bug dans la modification du FAM, on poura le tester et si c'est complet et ca fonctionne comme il faut, je crois qu'il faudra fermer cette issue...

**Comment by jgiacomini** [comment]
J'ai testé. Tout fonctionne bien. C'est top.
Merci.
